### ISSUE TITLE
Question: how to customize titlebar color?

### ISSUE THREAD

**Issue by Trikenstein** [EliverLara/Juno#35]
Using Juno dark. I have added this at the bottom of `~/.themes/Juno-standard-buttons/gtk-3.0/gtk.css`

```css
.titlebar, headerbar {
  background-color: #00827f;
}
.titlebar:backdrop, headerbar:backdrop {
  background-color: #004947;
}
```

This works partially. Only GTK3 apps could have colored titlebar. Strangely enough, Gnome terminal titlebar remains unaffected. GTK2 apps are insensitive to the above settings. Can you please show what CSS style should be modified to:

- Set terminal titlebar color
- GTK2 apps titlebar color

Thank you very much in advance for any help.
